env:
  browser: true
  node: true
parserOptions:
  ecmaVersion: 6
parser: 'babel-eslint'
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
